### ISSUE TITLE
Migrate from TypeScript to Golang

### ISSUE THREAD

**Issue by kharann** [dotkom/a3s#2]
Umbrella issue:

Preferably use 
- SQLBoiler, as a SQL client, to communicate with the existing database. Generates typesafe queries based on the current schema. Do this with the database repository pattern so that we can easily switch ORM to one which I include migrations later, such as Ent.go
- GQLgen for defining graphql schema and generating code that needs to be filled out. Currently the best GraphQL library of the one's I've tried
- Chi as the Router. Works great with std library. Also includes CORS and stuff
- Deploy with serverless-stack.com to AWS lambda. Also use this for lambda mocking and local development. Or use serverless framework :shrug: 
- Testify and stuff? 

Would also be cool:
- [Realtime](https://github.com/supabase/realtime) for displaying attendance registering with websockets. Completely separated from this service tho

Resources:

Learning Go: https://quii.gitbook.io/learn-go-with-tests
Repository pattern: https://threedots.tech/post/repository-pattern-in-go/
serverless golang: https://serverless-stack.com/examples/how-to-create-a-rest-api-in-golang-with-serverless.html

**Comment by matsjla** [comment]
Currently working on this in the https://github.com/dotkom/a3s/tree/rewrite branch

**Comment by magnusrodseth** [comment]
Manually closed, as the code base is now written in Go.
