### ISSUE TITLE
Ability to require a form filled in from participants before event start

### ISSUE THREAD

**Issue by NjaalSoerland** [dotkom/a3s#4]
In the same way an event can have a feedback-form where users must describe what they thought of the event, we should have the ability to require a form to be filled out by the participants before an event, as some events require additional information from the participants. Getting this information as it is now is very convoluted as it requires mailing all the participants to request this, and a lot of people have linked their online account to their student mail, which they never check.

As mentioned, a good solution for this would be to just reuse the functionality for feedback-forms, but have a deadline 24h or so before event start, rather than after the event.

**Comment by matsjla** [comment]
Discussed with @kharann - we want to keep feedback forms separate from this service (prefer to have it with another forms service).
